import { Component, OnInit, inject } from '@angular/core';
import { ActivatedRoute, RouterLink } from '@angular/router';
import { SeoService } from '../../core/services/seo.service';

interface IndustryDetail { slug: string; name: string; title: string; description: string; outcome: string; challenges: string[]; solution: string[]; }
const DATA: Record<string, IndustryDetail> = {
  'gyms-fitness': { slug:'gyms-fitness', name:'Gyms & Fitness', title:'Digital platforms for gyms that want more members and less manual work.', description:'Neelastack builds premium websites and custom web applications for gyms and fitness businesses — including memberships, class bookings, payments, member portals and admin tools.', outcome:'Help people discover your gym, understand your offer, book confidently and keep coming back.', challenges:['Your website does not explain your memberships clearly.','Customers still message or call to book classes and sessions.','Membership, payments and customer information live in separate places.','Your business looks smaller online than it really is.'], solution:['Premium gym website designed around membership conversion.','Online membership and class/session booking.','Member accounts and personalized experiences.','Payments, enquiries and admin workflows.','Search-friendly pages for local discovery.'] },
  'retail-ecommerce': { slug:'retail-ecommerce', name:'Retail & E-commerce', title:'Turn your store into a digital storefront that sells beyond your location.', description:'Build a premium ecommerce website for your retail business with product catalogues, checkout, payments, customer accounts, campaigns and order workflows.', outcome:'Reach customers beyond your physical store and make buying simple at any hour.', challenges:['Customers cannot browse your products online.','Orders and enquiries are handled manually.','Your brand needs a more premium online presence.','You want to sell beyond your local area.'], solution:['High-conversion storefront and product catalogue.','Secure checkout and payment integration.','Customer accounts and order tracking.','Campaign and landing-page capability.','SEO-friendly category and product content.'] },
  'restaurants-hospitality': { slug:'restaurants-hospitality', name:'Restaurants & Hospitality', title:'Give customers a better reason to discover, book and order from you.', description:'Neelastack creates premium digital experiences for restaurants and hospitality businesses with menus, reservations, online ordering, campaigns and local search foundations.', outcome:'Turn online attention into reservations, orders and repeat visits.', challenges:['Your online presence does not match the experience you deliver offline.','Customers need to call to reserve or enquire.','Your menu is difficult to discover or share.','You want more direct customer relationships.'], solution:['Premium website and digital menu.','Reservation and enquiry flows.','Online ordering and payments where appropriate.','Promotional landing pages and campaigns.','Local search-ready service and location content.'] },
  'healthcare-clinics': { slug:'healthcare-clinics', name:'Healthcare & Clinics', title:'A trusted digital front door for your clinic or healthcare practice.', description:'Build a professional healthcare website and booking experience that helps patients understand your services, discover your team and request appointments.', outcome:'Make choosing your practice easier while giving your team a cleaner digital workflow.', challenges:['Patients struggle to understand services or availability.','Appointment requests happen through calls and messages.','Important information is scattered across channels.','Your online presence does not reflect your practice quality.'], solution:['Professional service and practitioner pages.','Appointment and enquiry workflows.','Clear patient information architecture.','Secure integrations where required.','Search-friendly local and service content.'] },
  'professional-services': { slug:'professional-services', name:'Professional Services', title:'Turn expertise into a premium digital presence that generates qualified enquiries.', description:'Neelastack builds premium websites, lead-generation journeys, client portals and workflow systems for professional services businesses.', outcome:'Build credibility, capture intent and make the client journey easier.', challenges:['Your website explains what you do but does not create action.','Leads are scattered across email and messaging.','Client onboarding is repetitive.','You need a more credible digital presence.'], solution:['Positioning-led website and service pages.','Lead capture and qualification flows.','Consultation scheduling.','Client portal and document workflows.','Conversion-focused content architecture.'] },
  'startups': { slug:'startups', name:'Startups & New Ventures', title:'From idea to a credible digital product without building throwaway technology.', description:'Neelastack helps startups launch MVPs, customer portals and digital products with a production-minded architecture that can grow with the business.', outcome:'Validate faster, present your product professionally and create a technical foundation you can keep building on.', challenges:['You have a strong idea but need the product built.','A prototype needs to become production-ready.','You need to launch without creating a dead-end codebase.','You need one accountable partner across product and engineering.'], solution:['Product discovery and architecture.','MVP and customer-facing application build.','Authentication, payments and integrations.','Cloud deployment and automated testing.','A roadmap for the next stage of growth.'] },
};

@Component({ selector:'app-industry-detail', standalone:true, imports:[RouterLink], templateUrl:'./industry-detail.component.html', styleUrl:'./industry-detail.component.scss' })
export class IndustryDetailComponent implements OnInit {
  private route=inject(ActivatedRoute); private seo=inject(SeoService); industry?: IndustryDetail;
  ngOnInit():void { const slug=this.route.snapshot.paramMap.get('slug')??''; this.industry=DATA[slug]; if(!this.industry)return; this.seo.update({title:`${this.industry.name} Web & Software Solutions`,description:this.industry.description,path:`/industries/${this.industry.slug}`}); this.seo.setJsonLd([{ '@context':'https://schema.org','@type':'Service',name:`${this.industry.name} Web & Software Solutions`,description:this.industry.description,provider:{'@type':'Organization',name:'Neelastack',url:'https://neelastack.com'},areaServed:'IN'},{'@context':'https://schema.org','@type':'BreadcrumbList',itemListElement:[{'@type':'ListItem',position:1,name:'Industries',item:'https://neelastack.com/industries'},{'@type':'ListItem',position:2,name:this.industry.name,item:`https://neelastack.com/industries/${this.industry.slug}`}]}]); }
}
