import { Component, OnInit, inject, signal } from '@angular/core';
import { ActivatedRoute } from '@angular/router';
import { CommonModule, DecimalPipe } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { BookingService } from '../../../core/services/booking.service';
import { SeoService } from '../../../core/services/seo.service';
import { AvailabilityWindowDto, AvailabilityOverrideDto, BookingFunnelStatsDto, MeetingTypeDto, RevenueBySourceDto, LocationType } from '../../../core/models/booking.model';

@Component({ selector:'app-admin-booking-settings', standalone:true, imports:[CommonModule,FormsModule,DecimalPipe], templateUrl:'./admin-booking-settings.component.html', styleUrl:'./admin-booking-settings.component.scss' })
export class AdminBookingSettingsComponent implements OnInit {
  private booking=inject(BookingService); private seo=inject(SeoService); private route=inject(ActivatedRoute);
  meetingTypes=signal<MeetingTypeDto[]>([]); windows=signal<AvailabilityWindowDto[]>([]); overrides=signal<AvailabilityOverrideDto[]>([]); funnel=signal<BookingFunnelStatsDto|null>(null); revenue=signal<RevenueBySourceDto[]>([]); busy=signal(false); error=signal<string|null>(null); calendarEnabled=signal(false); calendarConnected=signal(false); calendarBusy=signal(false); calendarMessage=signal<string|null>(null);
  name=''; slug=''; duration=30; locationType: LocationType='GOOGLE_MEET'; price:number|null=null; day=1; start='10:00'; end='18:00'; timezone='Asia/Kolkata'; overrideDate=''; overrideAvailable=false; overrideStart='10:00'; overrideEnd='18:00'; overrideReason=''; overrideFrom=''; overrideTo='';
  ngOnInit(){this.seo.update({title:'Booking settings',description:'Configure meeting types, availability, calendar sync and analytics.',noindex:true}); const today=new Date(); this.overrideFrom=today.toISOString().slice(0,10); const to=new Date(today.getTime()+30*86400000); this.overrideTo=to.toISOString().slice(0,10); this.overrideDate=this.overrideFrom; this.reload(); this.loadCalendarStatus();}
  reload(){this.booking.listMeetingTypesAdmin().subscribe({next:v=>this.meetingTypes.set(v)});this.booking.listAvailabilityWindows().subscribe({next:v=>this.windows.set(v)});this.booking.funnelStats().subscribe({next:v=>this.funnel.set(v)});this.booking.revenueBySource().subscribe({next:v=>this.revenue.set(v)}); if(this.overrideFrom&&this.overrideTo)this.loadOverrides();}
  addMeeting(){if(!this.name.trim()||!this.slug.trim())return;this.busy.set(true);this.booking.createMeetingType({name:this.name.trim(),slug:this.slug.trim(),description:'',durationMinutes:this.duration,bufferBeforeMinutes:0,bufferAfterMinutes:0,minNoticeMinutes:60,maxHorizonDays:60,locationType:this.locationType,locationDetail:null,price:this.price,currency:'INR',requiresPayment:!!this.price,cancellableUntilHours:24,isActive:true,sortOrder:this.meetingTypes().length,formFields:[]}).subscribe({next:v=>{this.meetingTypes.set([...this.meetingTypes(),v]);this.name='';this.slug='';this.price=null;this.busy.set(false)},error:e=>{this.busy.set(false);this.error.set(e?.error?.message??'Could not create meeting type.')}})}
  deleteMeeting(id:string){if(!confirm('Delete this meeting type?'))return;this.booking.deleteMeetingType(id).subscribe({next:()=>this.meetingTypes.set(this.meetingTypes().filter(x=>x.id!==id)),error:e=>this.error.set(e?.error?.message??'Could not delete meeting type.')})}
  addWindow(){this.booking.addAvailabilityWindow(this.day,this.start+':00',this.end+':00',this.timezone).subscribe({next:v=>this.windows.set([...this.windows(),v]),error:e=>this.error.set(e?.error?.message??'Could not add availability.')})}
  deleteWindow(id:string){this.booking.removeAvailabilityWindow(id).subscribe({next:()=>this.windows.set(this.windows().filter(x=>x.id!==id)),error:e=>this.error.set(e?.error?.message??'Could not remove availability.')})}
  loadOverrides(){this.booking.listAvailabilityOverrides(this.overrideFrom,this.overrideTo).subscribe({next:v=>this.overrides.set(v),error:e=>this.error.set(e?.error?.message??'Could not load availability overrides.')});}
  saveOverride(){if(!this.overrideDate)return;this.booking.upsertAvailabilityOverride(this.overrideDate,this.overrideAvailable,this.overrideAvailable?this.overrideStart+':00':undefined,this.overrideAvailable?this.overrideEnd+':00':undefined,this.overrideReason.trim()||undefined).subscribe({next:()=>{this.loadOverrides();this.error.set(null)},error:e=>this.error.set(e?.error?.message??'Could not save override.')});}
  removeOverride(date:string){this.booking.removeAvailabilityOverride(date).subscribe({next:()=>this.loadOverrides(),error:e=>this.error.set(e?.error?.message??'Could not remove override.')});}
  loadCalendarStatus(){this.booking.calendarStatus().subscribe({next:v=>{this.calendarEnabled.set(v.featureEnabled);this.calendarConnected.set(v.connected)},error:e=>this.calendarMessage.set(e?.error?.message??'Could not load calendar status.')});}
  connectCalendar(){this.calendarBusy.set(true);this.booking.connectCalendar().subscribe({next:v=>window.location.assign(v.authorizationUrl),error:e=>{this.calendarBusy.set(false);this.calendarMessage.set(e?.error?.message??'Could not start Google Calendar connection.')}})}
  disconnectCalendar(){this.calendarBusy.set(true);this.booking.disconnectCalendar().subscribe({next:()=>{this.calendarBusy.set(false);this.calendarConnected.set(false)},error:e=>{this.calendarBusy.set(false);this.calendarMessage.set(e?.error?.message??'Could not disconnect Google Calendar.')}})}
  dayName(d:number){return ['','Monday','Tuesday','Wednesday','Thursday','Friday','Saturday','Sunday'][d]??String(d)}
}
