package com.neelastack.entity;

/** High-risk mutation types recorded by AuditLogService. See master prompt Section 2. */
public enum AuditAction {
    LEAD_STATUS_CHANGE,
    QUOTATION_CREATED,
    QUOTATION_DISPATCHED,
    QUOTATION_RESPONDED,
    INVOICE_UPDATED,
    PAYMENT_MARKED_PAID,
    WEBHOOK_REPLAYED,
    FILE_DELETED,
    MFA_MODIFIED,
    SESSION_REVOKED,
    PRICING_RULE_UPDATED,
    TESTIMONIAL_REQUEST_QUEUED,
    TESTIMONIAL_SUBMITTED,

    // --- Booking engine (see MeetingTypeService / BookingService) ---
    MEETING_TYPE_CREATED,
    MEETING_TYPE_UPDATED,
    MEETING_TYPE_DELETED,
    AVAILABILITY_UPDATED,
    BOOKING_CREATED,
    BOOKING_RESCHEDULED,
    BOOKING_CANCELLED,
    BOOKING_STATUS_CHANGED,
    BOOKING_OUTCOME_RECORDED,
    CALENDAR_CONNECTED,
    CALENDAR_DISCONNECTED
}
